apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app: argoCD
  name: argo
  namespace: rhacm-def
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchLabels:
      app: argoCD
