apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: argo-placement-rule
  namespace: rhacm-def
  labels:
    app: argoCD
spec:
  clusterSelector:
    matchLabels:
      argoCD: "yes"
  clusterReplicas: 1
