apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: petclinic-channel
  namespace: rhacm-channels
spec:
  type: Git
  pathname: https://github.com/gitops-jml/gitops-with-rhacm.git
#  secretRef:
#    name: git-secret
