apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: cp4i-channel
  namespace: cp4i-rhacm-manifests
spec:
  type: Git
  pathname: https://github.com/gitops-jml/gitops-with-rhacm.git
#  secretRef:
#    name: git-secret
