apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app: cp4i
  name: cp4i
  namespace: cp4i-rhacm-manifests
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchLabels:
      app: cp4i
