apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: petclinic-base-placement-rule
  namespace: petclinic
  labels:
    app: petclinic
    env: base
    group: group1
spec:
  clusterSelector:
    matchLabels:
      app: petclinic
      environment: base
  clusterReplicas: 1
