apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app: petclinic
    env: prod
  name: petclinic-prod-appli
  namespace: petclinic-lifecycle
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchLabels:
      app: petclinic
      env: prod
