apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: petclinic-prod-placement-rule
  namespace: petclinic
  labels:
    app: petclinic
    env: prod
spec:
  clusterSelector:
    matchLabels:
      app: petclinic
      environment: prod
  clusterReplicas: 1
