apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: catalog-source-placement-rule
  namespace: cp4i
  labels:
    app: cp4i
spec:
  clusterSelector:
    matchLabels:
      cp4i: "yes"
  clusterReplicas: 1
