apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  labels:
    app: rook-ceph
  name: rook-ceph-subscription
  annotations:
    apps.open-cluster-management.io/git-path: deployables/config/rook-ceph
    apps.open-cluster-management.io/git-branch: main
spec:
  channel: rook-ceph-channels/rook-ceph-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: rook-ceph-placement-rule
  secondaryChannel: ''
