apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  labels:
    app: rook-ceph
spec:
  channel: rook-ceph-channels/rook-ceph-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: rook-ceph-placement-rule
  secondaryChannel: ''
