apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app: rook-ceph
  name: rook-ceph
  namespace: rook-ceph
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchLabels:
      app: rook-ceph
