apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app: ibm-operator-catalog
  name: ibm-operator-catalog
  namespace: cp4i
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchLabels:
      app: ibm-operator-catalog
