apiVersion: apiconnect.ibm.com/v1beta1
kind: APIConnectCluster
metadata:
  name: apicluster
  labels:
    app.kubernetes.io/instance: apiconnect
    app.kubernetes.io/managed-by: ibm-apiconnect
    app.kubernetes.io/name: apicluster
  namespace: cp4i
spec:
  license:
    accept: true
    use: "nonproduction"
    license: L-RJON-C7BHW9
  profile: "n1xc2.m16"
  version: "10.0.4.0-ifix2-339"
  storageClassName: "rook-ceph-block"
  management:
    testAndMonitor:
      enabled: false
  gateway:      
    tokenManagementService:
      enabled: true
      storage:
        storageClassName: "rook-ceph-block"

