apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: sealed-secrets-placement-rule
  namespace: sealed-secrets
  labels:
    app: sealed-secrets
spec:
  clusterSelector:
    matchLabels:
      sealed-secrets: "yes"
