apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: sealed-secrets-subscription
  namespace: kube-system
  labels:
    app: sealed-secrets
  annotations:
    apps.open-cluster-management.io/git-path: deployables/config/sealed-secrets
    apps.open-cluster-management.io/git-branch: main
spec:
  channel: sealed-secrets-channels/sealed-secrets-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: sealed-secrets-placement-rule
  secondaryChannel: ''
