apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app: sealed-secrets
  name: sealed-secrets
  namespace: kube-system
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchLabels:
      app: sealed-secrets
