apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  labels:
    app: sealed-secrets
spec:
  channel: sealed-secrets-channels/rook-ceph-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: sealed-secrets-placement-rule
  secondaryChannel: ''
