apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  annotations:
  labels:
    app: gitops
  name: gitops-placement-1
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable