apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: gitops
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: gitops
    app.kubernetes.io/part-of: gitops
    apps.open-cluster-management.io/reconcile-rate: medium
  name: gitops-subscription-1
spec:
  channel: gitops-dep/githubcom-jtarte-rhacm
  overrides:
    - clusterName: /
      clusterOverrides:
        - path: metadata.namespace
          value: openshift-operators
  placement:
    placementRef:
      kind: PlacementRule
      name: gitops-placement-1
  secondaryChannel: ''